services:
  server:
    build: './back-end'
    ports:
      - "8080:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/Area

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  client_web:
    build: './front-end'
    depends_on:
      - server
    ports:
      - "8081:3001"
    volumes:
      - apk:/mobile_app/

volumes:
  apk:
  mongo_data: