version: '3'

services:

  server:
    build: './back-end'
    ports:
      - "8080:3030"

  client_web:
    build: './front-end'
    depends_on:
      - server
    ports:
      - "8081:3000"
    volumes:
      - apk:/mobile_app/

volumes:
  apk: