version: '3'

services:

  server:
    build: './back-end'
    ports:
      - "8080:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/Area"

  client_web:
    build: './front-end'
    depends_on:
      - server
    ports:
      - "8081:3001"
    volumes:
      - apk:/mobile_app/

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  apk:
  mongo-data: